sudo: required
services:
  - docker

before_install:
  - docker build -t lilcorey10/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run lilcorey10/react-test npm test -- --coverage

after_success:
  - docker build -t lilcorey10/multi-client ./client
  - docker build -t lilcorey10/multi-nginx ./nginx
  - docker build -t lilcorey10/multi-server ./server
  - docker build -t lilcorey10/multi-worker ./worker
  # Log into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push lilcorey10/multi-client
  - docker push lilcorey10/multi-nginx
  - docker push lilcorey10/multi-server
  - docker push lilcorey10/multi-worker

